### ISSUE TITLE
프로젝트 계획

### ISSUE THREAD

**Issue by yeonjuan** [yeonjuan/Typescript-Handbook-ko#126]
프로젝트의 앞으로 계획이 필요할 것 같아 정리합니다. **누구나** 계획에 관해서 코멘트로 의견 남겨주시면, 논의를 통해 수정하도록 하겠습니다.

프로젝트의 최종 목표는 **[TypeScript 공식문서 - Document 탭](https://www.typescriptlang.org/docs/home.html)에 있는 문서를 모두 번역**하는 것입니다. 한번에 모두 진행하는 것보다는 단계를 나눠진행하려 합니다.

### v1
- 진행중인 Handbook 번역 완료 (이하 미완료 목록)
   - [x] : module resolution - #112
   - [x] : decorators - #111 
   - [x] : type checking javascript files - #110 
   - [x] : utility types - #109 
   - [x] : namespaces and modules - #100 
   - [x] : advanced types - #63 
   - [x] : mixins - #58 

- 핸드북 웹 페이지
  gitbook 을 이용해 페이지를 제작하는 것을 고려중입니다. (순서대로 진행)
    - [x] : 1. 프로젝트 문서 디렉터리 구조 정하기 - [코멘트](https://github.com/yeonjuan/Typescript-Handbook-ko/issues/126#issuecomment-596052426)
    - [x] : 2. 프로젝트 구조에 따라 변경(진행중인 문서가 모두 번역된 뒤 진행) 
    - [x] : 3. 페이지 제작
    - [x] : 4. github page 에 배포
    - [x] : 5.  페이지 빌드, 배포 과정을 스크립트로 자동화

### v2
 - tutorials 번역

   - [x] : TypeScript in 5 minutes - #138 
   - [ ] : ASP.NET Core - #139 
   - [ ] : Gulp - #140 
   - [ ] : Migrating from JavaScript - #141 
   - [x] : React & Webpack - #142 

### v3
 - declaration files 번역 

   - [x] : Introduction - #143  
   - [x] : Library Structures - #144
   - [x] : By Example - #145 
   - [x] : Do's and Don'ts - #146
   - [x] : Deep Dive - #147 
   - [x] : Templates - #148
   - [x] : Publishing - #149
   - [x] : Consumption - #150  

### v4 
 - project configuration 번역

   - [ ] : tsconfig.json - #215 
   - [ ] : Compiler Options - #216 
   - [ ] : Project References - #217 
   - [ ] : Compiler Options in MS Build - #218
   - [ ] : Integrating with Build Tools - #219
   - [ ] : Nightly Builds - #220

**Comment by bumkeyy** [comment]
@yeonjuan @guyeol  
핸드북 웹페이지 작업과 별도로 
나머지 부분도 번역 작업이 진행되도록 미리 원문을 올려놓는 건 어떨까요? 😄

**Comment by yeonjuan** [comment]
### Gitbook 계획 + 프로젝트 문서 디렉터리 구조 정하기
* 프로젝트 문서 구조
```
/
|- ...
|- handbook/ ...
|- tutorials/ ...
|- declaration-files/ ...
|- project-configuration /... 
|- release-notes/ ...
|- ....
```

* gitbook
 - Edit 버튼 (github md 파일 수정링크로 연결) - [edit-link-plugin](https://github.com/rtCamp/gitbook-plugin-edit-link)

**Comment by pocojang** [comment]
@yeonjuan 

안녕하세요!

[기존 TypeScript Handbook 한글 문서](https://github.com/typescript-kr/typescript-kr.github.io)를 번역하던 장현석이라고 합니다

현재 1차적인 번역 완료 후 지속적으로 번역 수정 및 요청이 들어오고 있지만
멤버들이 모두 바빠진 관계로 몇년동안 제대로 관리를 하지 못하고 있는 상황입니다.

때문에 저희 오거나이저를 아카이빙하고 링크를 통해 현재 번역 중이신 곳을 안내해드릴지
아니면 오거나이저를 넘겨드리는 방법도 있고 (처음에 SEO에 문제가 있었는데 최근들어서는 SEO 및 GA가 많이 활성화되어 있어 아쉬운 상태입니다)
다양한 형태로 이런 좋은 프로젝트를 이어나갔으면 좋겠습니다.

이슈 쓰레드 혹은 받는 사람 devjang2016@gmail.com & ysm0622@gmail.com
으로 이메일 주시면 감사하겠습니다.

**Comment by yeonjuan** [comment]
@devJang 
같이 이 레포를 관리하시는 분들이 계신데, 오늘 이야기후에 메일 드리겠습니다! 감사합니다
cc @guyeol , @Bumkeyy , @dvlprsh
